project_id = "svadrczzdvdbeajeiabs"

[functions.multi-agent-build]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.project-storage]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.app-api]
verify_jwt = false

[functions.visual-edit]
verify_jwt = false

[functions.supabase-oauth]
verify_jwt = false

[functions.execute-migration]
verify_jwt = false

[functions.db-agent]
verify_jwt = false
