project_id = "svadrczzdvdbeajeiabs"

[functions.multi-agent-build]
verify_jwt = false

[functions.generate-code]
verify_jwt = false

[functions.project-storage]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.app-api]
verify_jwt = false

[functions.visual-edit]
verify_jwt = false

[functions.supabase-oauth]
verify_jwt = false

[functions.execute-migration]
verify_jwt = false

[functions.db-agent]
verify_jwt = false

[functions.create-sandbox]
verify_jwt = false

[functions.apply-code]
verify_jwt = false

[functions.get-sandbox-files]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.firecrawl-search]
verify_jwt = false

[functions.generate-ai-code]
verify_jwt = false

[functions.sandbox-proxy]
verify_jwt = false

[functions.execute-user-sql]
verify_jwt = false
